PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
#select (COUNT(?s) AS ?c) 
select *
from <http://w3id.org/snomed>
{
    
    ?s rdfs:subClassOf <http://snomed.info/id/138875005> .
    ?s 	skos:prefLabel ?label .
} 

